.TH "graphics.GraphicsError" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.GraphicsError \- Module Exceptions\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 
Module Exceptions\&. 


.PP
.nf
Generic error class for graphics module exceptions\&.
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
