.TH "graphics.Circle" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.Circle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgraphics\&.Oval\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, center, radius)"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.ti -1c
.RI "def \fBclone\fP (self)"
.br
.ti -1c
.RI "def \fBgetRadius\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBradius\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def graphics\&.Circle\&.__init__ ( self,  center,  radius)"

.PP
Reimplemented from \fBgraphics\&.Oval\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def graphics\&.Circle\&.__repr__ ( self)"

.PP
Reimplemented from \fBgraphics\&.Oval\fP\&.
.SS "def graphics\&.Circle\&.clone ( self)"

.PP
Reimplemented from \fBgraphics\&.Oval\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
