.TH "graphics._BBox" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics._BBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgraphics\&.GraphicsObject\fP\&.
.PP
Inherited by \fBgraphics\&.Line\fP, \fBgraphics\&.Oval\fP, and \fBgraphics\&.Rectangle\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, p1, p2, options=['outline','width','fill'])"
.br
.ti -1c
.RI "def \fBgetP1\fP (self)"
.br
.ti -1c
.RI "def \fBgetP2\fP (self)"
.br
.ti -1c
.RI "def \fBgetCenter\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBp1\fP"
.br
.ti -1c
.RI "\fBp2\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def graphics\&._BBox\&.__init__ ( self,  p1,  p2,  options = \fC['outline','width','fill']\fP)"

.PP
Reimplemented from \fBgraphics\&.GraphicsObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
