.TH "buttons.RestorePosition" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buttons.RestorePosition \- \fBButton\fP used the restore the position\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbuttons\&.Button\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, win, c1, c2, m, start_x, end_x, start_y, end_y, txt)"
.br
.ti -1c
.RI "def \fBdraw_button\fP (self)"
.br
.ti -1c
.RI "def \fBundraw_button\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBwin\fP"
.br
.ti -1c
.RI "\fBis_active\fP"
.br
.ti -1c
.RI "\fBstart_x\fP"
.br
.ti -1c
.RI "\fBend_x\fP"
.br
.ti -1c
.RI "\fBstart_y\fP"
.br
.ti -1c
.RI "\fBend_y\fP"
.br
.ti -1c
.RI "\fBbutton\fP"
.br
.ti -1c
.RI "\fBtxt\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBButton\fP used the restore the position\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def buttons\&.RestorePosition\&.__init__ ( self,  win,  c1,  c2,  m,  start_x,  end_x,  start_y,  end_y,  txt)"

.PP
Reimplemented from \fBbuttons\&.Button\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def buttons\&.RestorePosition\&.draw_button ( self)"

.PP
Reimplemented from \fBbuttons\&.Button\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
