.TH "buttons.prevButton" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
buttons.prevButton \- \fBButton\fP used the forward the position by one move\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbuttons\&.Button\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, win, c1, c2, size, m, start_x, start_y)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBprev_p1\fP"
.br
.ti -1c
.RI "\fBprev_p2\fP"
.br
.ti -1c
.RI "\fBend_x\fP"
.br
.ti -1c
.RI "\fBend_y\fP"
.br
.ti -1c
.RI "\fBbutton\fP"
.br
.ti -1c
.RI "\fBbutton_t\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBButton\fP used the forward the position by one move\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def buttons\&.prevButton\&.__init__ ( self,  win,  c1,  c2,  size,  m,  start_x,  start_y)"

.PP
Reimplemented from \fBbuttons\&.Button\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
