.TH "graphics.Entry" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.Entry
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgraphics\&.GraphicsObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, p, width)"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.ti -1c
.RI "def \fBgetText\fP (self)"
.br
.ti -1c
.RI "def \fBgetAnchor\fP (self)"
.br
.ti -1c
.RI "def \fBclone\fP (self)"
.br
.ti -1c
.RI "def \fBsetText\fP (self, t)"
.br
.ti -1c
.RI "def \fBsetFill\fP (self, color)"
.br
.ti -1c
.RI "def \fBsetFace\fP (self, face)"
.br
.ti -1c
.RI "def \fBsetSize\fP (self, size)"
.br
.ti -1c
.RI "def \fBsetStyle\fP (self, style)"
.br
.ti -1c
.RI "def \fBsetTextColor\fP (self, color)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBanchor\fP"
.br
.ti -1c
.RI "\fBwidth\fP"
.br
.ti -1c
.RI "\fBtext\fP"
.br
.ti -1c
.RI "\fBfill\fP"
.br
.ti -1c
.RI "\fBcolor\fP"
.br
.ti -1c
.RI "\fBfont\fP"
.br
.ti -1c
.RI "\fBentry\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def graphics\&.Entry\&.__init__ ( self,  p,  width)"

.PP
Reimplemented from \fBgraphics\&.GraphicsObject\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "def graphics\&.Entry\&.setFill ( self,  color)"

.PP
.nf
Set interior color to color
.fi
.PP
 
.PP
Reimplemented from \fBgraphics\&.GraphicsObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
