.TH "graphics.Transform" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.Transform
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, w, h, xlow, ylow, xhigh, yhigh)"
.br
.ti -1c
.RI "def \fBscreen\fP (self, x, y)"
.br
.ti -1c
.RI "def \fBworld\fP (self, xs, ys)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBxbase\fP"
.br
.ti -1c
.RI "\fBybase\fP"
.br
.ti -1c
.RI "\fBxscale\fP"
.br
.ti -1c
.RI "\fByscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Internal class for 2-D coordinate transformations
.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
