.TH "graphics.Polygon" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.Polygon
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgraphics\&.GraphicsObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, *points)"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.ti -1c
.RI "def \fBclone\fP (self)"
.br
.ti -1c
.RI "def \fBgetPoints\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpoints\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def graphics\&.Polygon\&.__init__ ( self, * points)"

.PP
Reimplemented from \fBgraphics\&.GraphicsObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
