.TH "graphics.Rectangle" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.Rectangle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgraphics\&._BBox\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, p1, p2)"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.ti -1c
.RI "def \fBclone\fP (self)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def graphics\&.Rectangle\&.__init__ ( self,  p1,  p2)"

.PP
Reimplemented from \fBgraphics\&._BBox\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
