.TH "graphics.Point" 3 "Mon Dec 19 2022" "Chess App" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.Point
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBgraphics\&.GraphicsObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, x, y)"
.br
.ti -1c
.RI "def \fB__repr__\fP (self)"
.br
.ti -1c
.RI "def \fBclone\fP (self)"
.br
.ti -1c
.RI "def \fBgetX\fP (self)"
.br
.ti -1c
.RI "def \fBgetY\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsetFill\fP"
.br
.ti -1c
.RI "\fBx\fP"
.br
.ti -1c
.RI "\fBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def graphics\&.Point\&.__init__ ( self,  x,  y)"

.PP
Reimplemented from \fBgraphics\&.GraphicsObject\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Chess App from the source code\&.
